# After changing this file, check it on:
#   http://lint.travis-ci.org/
sudo: false

language: python

# Python versions to be tested
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libsuitesparse-dev
    - libgdal-dev
    - graphviz
    - mono-devel

env:
  global:
    - PIP_INSTALL="pip install --upgrade"

before_install:
  - $PIP_INSTALL pip
  - uname -a
  - printenv
  # The next two lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm


install:
  - $PIP_INSTALL atlas numpy scipy matplotlib nose dateutil pandas statsmodels networkx fnss

script:
  - nosetests
